
export const items = [
    {
        id: 1,
        title: 'Корпоративное право',
        description: 'Инвестирование: способы, риски, субъекты : монография',
        author: 'Майфат А.В.',
        price: 4450,
        star: 4.9,
        recomend: 89,
        image: 'image/image 142.png',
        bestseller: 'Бестселлер',
        discount: '1+1=3'
    },
    {
        id: 2,
        title: 'Договорное право',
        description: 'Договор коммерческой концессии (франчайзинг). Граж...',
        author: 'Багдасарян А.Ф.',
        price: 372,
        star: 4.9,
        recomend: 89,
        stocks: 'Новинка',
        image: 'image/imageRo.png',
    },
    {
        id: 3,
        title: 'Конкурентное право',
        description: 'Договор коммерческой концессии (франчайзинг). Граж...',
        author: 'Башлаков-Николаев И.В.',
        price: 984,
        star: 4.9,
        recomend: 89,
        image: 'image/image145.png',
        oldprice: '1 200',
        pricediscount: '1 200'
    },
    {
        id: 4,
        title: 'Корпоративное право',
        description: 'Инвестирование: способы, риски, субъекты : монография',
        author: 'Майфат А.В.',
        price: '450',
        star: 4.9,
        recomend: 89,
        image: 'image/image 142.png',
    },
    {
        id: 5,
        title: 'Корпоративное право',
        description: 'Инвестирование: способы, риски, субъекты : монография',
        author: 'Майфат А.В.',
        price: '450',
        star: 4.9,
        recomend: 89,
        image: 'image/image 142.png',
    },
    {
        id: 6,
        title: 'Корпоративное право',
        description: 'Инвестирование: способы, риски, субъекты : монография',
        author: 'Майфат А.В.',
        price: '450',
        star: 4.9,
        recomend: 89,
        image: 'image/image 142.png',
    },
    

]